// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/letraz/v1/callback.proto

package letrazv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        *string                `protobuf:"bytes,1,opt,name=engine,proto3,oneof" json:"engine,omitempty"`
	Url           *string                `protobuf:"bytes,2,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackMetadataRequest) Reset() {
	*x = CallbackMetadataRequest{}
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackMetadataRequest) ProtoMessage() {}

func (x *CallbackMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackMetadataRequest.ProtoReflect.Descriptor instead.
func (*CallbackMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_callback_proto_rawDescGZIP(), []int{0}
}

func (x *CallbackMetadataRequest) GetEngine() string {
	if x != nil && x.Engine != nil {
		return *x.Engine
	}
	return ""
}

func (x *CallbackMetadataRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type JobDetailRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	JobUrl           string                 `protobuf:"bytes,2,opt,name=job_url,json=jobUrl,proto3" json:"job_url,omitempty"`
	CompanyName      string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Location         string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Salary           *JobSalaryRequest      `protobuf:"bytes,5,opt,name=salary,proto3,oneof" json:"salary,omitempty"`
	Requirements     []string               `protobuf:"bytes,6,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Description      string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Responsibilities []string               `protobuf:"bytes,8,rep,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Benefits         []string               `protobuf:"bytes,9,rep,name=benefits,proto3" json:"benefits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobDetailRequest) Reset() {
	*x = JobDetailRequest{}
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetailRequest) ProtoMessage() {}

func (x *JobDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetailRequest.ProtoReflect.Descriptor instead.
func (*JobDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_callback_proto_rawDescGZIP(), []int{1}
}

func (x *JobDetailRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobDetailRequest) GetJobUrl() string {
	if x != nil {
		return x.JobUrl
	}
	return ""
}

func (x *JobDetailRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *JobDetailRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobDetailRequest) GetSalary() *JobSalaryRequest {
	if x != nil {
		return x.Salary
	}
	return nil
}

func (x *JobDetailRequest) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *JobDetailRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobDetailRequest) GetResponsibilities() []string {
	if x != nil {
		return x.Responsibilities
	}
	return nil
}

func (x *JobDetailRequest) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

type JobSalaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *string                `protobuf:"bytes,1,opt,name=currency,proto3,oneof" json:"currency,omitempty"`
	Max           *int32                 `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	Min           *int32                 `protobuf:"varint,3,opt,name=min,proto3,oneof" json:"min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSalaryRequest) Reset() {
	*x = JobSalaryRequest{}
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSalaryRequest) ProtoMessage() {}

func (x *JobSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSalaryRequest.ProtoReflect.Descriptor instead.
func (*JobSalaryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_callback_proto_rawDescGZIP(), []int{2}
}

func (x *JobSalaryRequest) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *JobSalaryRequest) GetMax() int32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *JobSalaryRequest) GetMin() int32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

type ScrapeJobCallbackRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	ProcessId      string                   `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	Status         string                   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Data           *ScrapeJobDataRequest    `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Timestamp      string                   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Operation      string                   `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	ProcessingTime string                   `protobuf:"bytes,6,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	Metadata       *CallbackMetadataRequest `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScrapeJobCallbackRequest) Reset() {
	*x = ScrapeJobCallbackRequest{}
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeJobCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeJobCallbackRequest) ProtoMessage() {}

func (x *ScrapeJobCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeJobCallbackRequest.ProtoReflect.Descriptor instead.
func (*ScrapeJobCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_callback_proto_rawDescGZIP(), []int{3}
}

func (x *ScrapeJobCallbackRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ScrapeJobCallbackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScrapeJobCallbackRequest) GetData() *ScrapeJobDataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScrapeJobCallbackRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ScrapeJobCallbackRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ScrapeJobCallbackRequest) GetProcessingTime() string {
	if x != nil {
		return x.ProcessingTime
	}
	return ""
}

func (x *ScrapeJobCallbackRequest) GetMetadata() *CallbackMetadataRequest {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScrapeJobDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *JobDetailRequest      `protobuf:"bytes,1,opt,name=job,proto3,oneof" json:"job,omitempty"`
	Engine        *string                `protobuf:"bytes,2,opt,name=engine,proto3,oneof" json:"engine,omitempty"`
	UsedLlm       *bool                  `protobuf:"varint,3,opt,name=used_llm,json=usedLlm,proto3,oneof" json:"used_llm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeJobDataRequest) Reset() {
	*x = ScrapeJobDataRequest{}
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeJobDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeJobDataRequest) ProtoMessage() {}

func (x *ScrapeJobDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeJobDataRequest.ProtoReflect.Descriptor instead.
func (*ScrapeJobDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_callback_proto_rawDescGZIP(), []int{4}
}

func (x *ScrapeJobDataRequest) GetJob() *JobDetailRequest {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *ScrapeJobDataRequest) GetEngine() string {
	if x != nil && x.Engine != nil {
		return *x.Engine
	}
	return ""
}

func (x *ScrapeJobDataRequest) GetUsedLlm() bool {
	if x != nil && x.UsedLlm != nil {
		return *x.UsedLlm
	}
	return false
}

type ScrapeJobCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           *string                `protobuf:"bytes,1,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeJobCallbackResponse) Reset() {
	*x = ScrapeJobCallbackResponse{}
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeJobCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeJobCallbackResponse) ProtoMessage() {}

func (x *ScrapeJobCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_callback_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeJobCallbackResponse.ProtoReflect.Descriptor instead.
func (*ScrapeJobCallbackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_callback_proto_rawDescGZIP(), []int{5}
}

func (x *ScrapeJobCallbackResponse) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

var File_api_proto_letraz_v1_callback_proto protoreflect.FileDescriptor

const file_api_proto_letraz_v1_callback_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/letraz/v1/callback.proto\x12\x11letraz_server.JOB\"`\n" +
	"\x17CallbackMetadataRequest\x12\x1b\n" +
	"\x06engine\x18\x01 \x01(\tH\x00R\x06engine\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x02 \x01(\tH\x01R\x03url\x88\x01\x01B\t\n" +
	"\a_engineB\x06\n" +
	"\x04_url\"\xdb\x02\n" +
	"\x10JobDetailRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x17\n" +
	"\ajob_url\x18\x02 \x01(\tR\x06jobUrl\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12@\n" +
	"\x06salary\x18\x05 \x01(\v2#.letraz_server.JOB.JobSalaryRequestH\x00R\x06salary\x88\x01\x01\x12\"\n" +
	"\frequirements\x18\x06 \x03(\tR\frequirements\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12*\n" +
	"\x10responsibilities\x18\b \x03(\tR\x10responsibilities\x12\x1a\n" +
	"\bbenefits\x18\t \x03(\tR\bbenefitsB\t\n" +
	"\a_salary\"~\n" +
	"\x10JobSalaryRequest\x12\x1f\n" +
	"\bcurrency\x18\x01 \x01(\tH\x00R\bcurrency\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x05H\x01R\x03max\x88\x01\x01\x12\x15\n" +
	"\x03min\x18\x03 \x01(\x05H\x02R\x03min\x88\x01\x01B\v\n" +
	"\t_currencyB\x06\n" +
	"\x04_maxB\x06\n" +
	"\x04_min\"\xda\x02\n" +
	"\x18ScrapeJobCallbackRequest\x12\x1c\n" +
	"\tprocessId\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12@\n" +
	"\x04data\x18\x03 \x01(\v2'.letraz_server.JOB.ScrapeJobDataRequestH\x00R\x04data\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12'\n" +
	"\x0fprocessing_time\x18\x06 \x01(\tR\x0eprocessingTime\x12K\n" +
	"\bmetadata\x18\a \x01(\v2*.letraz_server.JOB.CallbackMetadataRequestH\x01R\bmetadata\x88\x01\x01B\a\n" +
	"\x05_dataB\v\n" +
	"\t_metadata\"\xaf\x01\n" +
	"\x14ScrapeJobDataRequest\x12:\n" +
	"\x03job\x18\x01 \x01(\v2#.letraz_server.JOB.JobDetailRequestH\x00R\x03job\x88\x01\x01\x12\x1b\n" +
	"\x06engine\x18\x02 \x01(\tH\x01R\x06engine\x88\x01\x01\x12\x1e\n" +
	"\bused_llm\x18\x03 \x01(\bH\x02R\ausedLlm\x88\x01\x01B\x06\n" +
	"\x04_jobB\t\n" +
	"\a_engineB\v\n" +
	"\t_used_llm\":\n" +
	"\x19ScrapeJobCallbackResponse\x12\x15\n" +
	"\x03msg\x18\x01 \x01(\tH\x00R\x03msg\x88\x01\x01B\x06\n" +
	"\x04_msg2\x8f\x01\n" +
	"\x1bScrapeJobCallbackController\x12p\n" +
	"\x11ScrapeJobCallBack\x12+.letraz_server.JOB.ScrapeJobCallbackRequest\x1a,.letraz_server.JOB.ScrapeJobCallbackResponse\"\x00B+Z)letraz-utils/api/proto/letraz/v1;letrazv1b\x06proto3"

var (
	file_api_proto_letraz_v1_callback_proto_rawDescOnce sync.Once
	file_api_proto_letraz_v1_callback_proto_rawDescData []byte
)

func file_api_proto_letraz_v1_callback_proto_rawDescGZIP() []byte {
	file_api_proto_letraz_v1_callback_proto_rawDescOnce.Do(func() {
		file_api_proto_letraz_v1_callback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_letraz_v1_callback_proto_rawDesc), len(file_api_proto_letraz_v1_callback_proto_rawDesc)))
	})
	return file_api_proto_letraz_v1_callback_proto_rawDescData
}

var file_api_proto_letraz_v1_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_letraz_v1_callback_proto_goTypes = []any{
	(*CallbackMetadataRequest)(nil),   // 0: letraz_server.JOB.CallbackMetadataRequest
	(*JobDetailRequest)(nil),          // 1: letraz_server.JOB.JobDetailRequest
	(*JobSalaryRequest)(nil),          // 2: letraz_server.JOB.JobSalaryRequest
	(*ScrapeJobCallbackRequest)(nil),  // 3: letraz_server.JOB.ScrapeJobCallbackRequest
	(*ScrapeJobDataRequest)(nil),      // 4: letraz_server.JOB.ScrapeJobDataRequest
	(*ScrapeJobCallbackResponse)(nil), // 5: letraz_server.JOB.ScrapeJobCallbackResponse
}
var file_api_proto_letraz_v1_callback_proto_depIdxs = []int32{
	2, // 0: letraz_server.JOB.JobDetailRequest.salary:type_name -> letraz_server.JOB.JobSalaryRequest
	4, // 1: letraz_server.JOB.ScrapeJobCallbackRequest.data:type_name -> letraz_server.JOB.ScrapeJobDataRequest
	0, // 2: letraz_server.JOB.ScrapeJobCallbackRequest.metadata:type_name -> letraz_server.JOB.CallbackMetadataRequest
	1, // 3: letraz_server.JOB.ScrapeJobDataRequest.job:type_name -> letraz_server.JOB.JobDetailRequest
	3, // 4: letraz_server.JOB.ScrapeJobCallbackController.ScrapeJobCallBack:input_type -> letraz_server.JOB.ScrapeJobCallbackRequest
	5, // 5: letraz_server.JOB.ScrapeJobCallbackController.ScrapeJobCallBack:output_type -> letraz_server.JOB.ScrapeJobCallbackResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_letraz_v1_callback_proto_init() }
func file_api_proto_letraz_v1_callback_proto_init() {
	if File_api_proto_letraz_v1_callback_proto != nil {
		return
	}
	file_api_proto_letraz_v1_callback_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_letraz_v1_callback_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_letraz_v1_callback_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_letraz_v1_callback_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_letraz_v1_callback_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_letraz_v1_callback_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_letraz_v1_callback_proto_rawDesc), len(file_api_proto_letraz_v1_callback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_letraz_v1_callback_proto_goTypes,
		DependencyIndexes: file_api_proto_letraz_v1_callback_proto_depIdxs,
		MessageInfos:      file_api_proto_letraz_v1_callback_proto_msgTypes,
	}.Build()
	File_api_proto_letraz_v1_callback_proto = out.File
	file_api_proto_letraz_v1_callback_proto_goTypes = nil
	file_api_proto_letraz_v1_callback_proto_depIdxs = nil
}
