// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/letraz/v1/letraz-utils.proto

package letrazv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapeJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Options       *ScrapeOptions         `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeJobRequest) Reset() {
	*x = ScrapeJobRequest{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeJobRequest) ProtoMessage() {}

func (x *ScrapeJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeJobRequest.ProtoReflect.Descriptor instead.
func (*ScrapeJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeJobRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ScrapeJobRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ScrapeJobRequest) GetOptions() *ScrapeOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ScrapeJobResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProcessId string                 `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"` // Process ID for async tracking (camelCase to match REST)
	Status    string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`       // ACCEPTED, FAILURE
	Message   string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`     // Status message
	Timestamp string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO timestamp string (to match REST format)
	// Optional error fields (only for failures)
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // Error code/type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeJobResponse) Reset() {
	*x = ScrapeJobResponse{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeJobResponse) ProtoMessage() {}

func (x *ScrapeJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeJobResponse.ProtoReflect.Descriptor instead.
func (*ScrapeJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeJobResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ScrapeJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScrapeJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScrapeJobResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ScrapeJobResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BaseResume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Base          bool                   `protobuf:"varint,2,opt,name=base,proto3" json:"base,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Sections      []*ResumeSection       `protobuf:"bytes,4,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResume) Reset() {
	*x = BaseResume{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResume) ProtoMessage() {}

func (x *BaseResume) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResume.ProtoReflect.Descriptor instead.
func (*BaseResume) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseResume) GetBase() bool {
	if x != nil {
		return x.Base
	}
	return false
}

func (x *BaseResume) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *BaseResume) GetSections() []*ResumeSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // nullable in JSON
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Dob           string                 `protobuf:"bytes,7,opt,name=dob,proto3" json:"dob,omitempty"`                 // nullable in JSON
	Nationality   string                 `protobuf:"bytes,8,opt,name=nationality,proto3" json:"nationality,omitempty"` // nullable in JSON
	Address       string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	Postal        string                 `protobuf:"bytes,11,opt,name=postal,proto3" json:"postal,omitempty"`
	Country       string                 `protobuf:"bytes,12,opt,name=country,proto3" json:"country,omitempty"` // nullable in JSON
	Website       string                 `protobuf:"bytes,13,opt,name=website,proto3" json:"website,omitempty"`
	ProfileText   string                 `protobuf:"bytes,14,opt,name=profile_text,json=profileText,proto3" json:"profile_text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO timestamp string
	UpdatedAt     string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ISO timestamp string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *User) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *User) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *User) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *User) GetPostal() string {
	if x != nil {
		return x.Postal
	}
	return ""
}

func (x *User) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *User) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *User) GetProfileText() string {
	if x != nil {
		return x.ProfileText
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ResumeSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resume        string                 `protobuf:"bytes,2,opt,name=resume,proto3" json:"resume,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // Structured data (JSON-like) instead of string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSection) Reset() {
	*x = ResumeSection{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSection) ProtoMessage() {}

func (x *ResumeSection) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSection.ProtoReflect.Descriptor instead.
func (*ResumeSection) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeSection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResumeSection) GetResume() string {
	if x != nil {
		return x.Resume
	}
	return ""
}

func (x *ResumeSection) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ResumeSection) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResumeSection) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type TailorResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResume    *BaseResume            `protobuf:"bytes,1,opt,name=base_resume,json=baseResume,proto3" json:"base_resume,omitempty"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	ResumeId      string                 `protobuf:"bytes,3,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailorResumeRequest) Reset() {
	*x = TailorResumeRequest{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResumeRequest) ProtoMessage() {}

func (x *TailorResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResumeRequest.ProtoReflect.Descriptor instead.
func (*TailorResumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{5}
}

func (x *TailorResumeRequest) GetBaseResume() *BaseResume {
	if x != nil {
		return x.BaseResume
	}
	return nil
}

func (x *TailorResumeRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *TailorResumeRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

type TailorResumeResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProcessId string                 `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"` // Process ID for async tracking (camelCase to match REST)
	Status    string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`       // ACCEPTED, FAILURE
	Message   string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`     // Status message
	Timestamp string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO timestamp string (to match REST format)
	// Optional error fields (only for failures)
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // Error code/type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailorResumeResponse) Reset() {
	*x = TailorResumeResponse{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResumeResponse) ProtoMessage() {}

func (x *TailorResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResumeResponse.ProtoReflect.Descriptor instead.
func (*TailorResumeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{6}
}

func (x *TailorResumeResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *TailorResumeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TailorResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TailorResumeResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TailorResumeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResumeScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      string                 `protobuf:"bytes,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"` // Resume ID to generate screenshot for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeScreenshotRequest) Reset() {
	*x = ResumeScreenshotRequest{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeScreenshotRequest) ProtoMessage() {}

func (x *ResumeScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ResumeScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeScreenshotRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

type ResumeScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                    // ACCEPTED, SUCCESS, FAILURE
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // Status message
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                              // ISO timestamp string
	ProcessId     string                 `protobuf:"bytes,4,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`             // Process ID for async tracking (for ACCEPTED status)
	ScreenshotUrl string                 `protobuf:"bytes,5,opt,name=screenshot_url,json=screenshotUrl,proto3" json:"screenshot_url,omitempty"` // CDN URL of the generated screenshot (only for SUCCESS status)
	// Optional error fields (only for failures)
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // Error code/type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeScreenshotResponse) Reset() {
	*x = ResumeScreenshotResponse{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeScreenshotResponse) ProtoMessage() {}

func (x *ResumeScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ResumeScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{8}
}

func (x *ResumeScreenshotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResumeScreenshotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResumeScreenshotResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ResumeScreenshotResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ResumeScreenshotResponse) GetScreenshotUrl() string {
	if x != nil {
		return x.ScreenshotUrl
	}
	return ""
}

func (x *ResumeScreenshotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{9}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                           // health status (healthy, unhealthy)
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                     // ISO timestamp string
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                                         // service version
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`                                       // uptime in seconds
	Checks        map[string]string      `protobuf:"bytes,5,rep,name=checks,proto3" json:"checks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // health check results for various components
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetChecks() map[string]string {
	if x != nil {
		return x.Checks
	}
	return nil
}

type Job struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	JobUrl           string                 `protobuf:"bytes,3,opt,name=job_url,json=jobUrl,proto3" json:"job_url,omitempty"`
	CompanyName      string                 `protobuf:"bytes,4,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Location         string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Salary           *Salary                `protobuf:"bytes,6,opt,name=salary,proto3" json:"salary,omitempty"`
	Requirements     []string               `protobuf:"bytes,7,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Description      string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Responsibilities []string               `protobuf:"bytes,9,rep,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Benefits         []string               `protobuf:"bytes,10,rep,name=benefits,proto3" json:"benefits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{11}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetJobUrl() string {
	if x != nil {
		return x.JobUrl
	}
	return ""
}

func (x *Job) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Job) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Job) GetSalary() *Salary {
	if x != nil {
		return x.Salary
	}
	return nil
}

func (x *Job) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetResponsibilities() []string {
	if x != nil {
		return x.Responsibilities
	}
	return nil
}

func (x *Job) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

type Salary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Min           int32                  `protobuf:"varint,3,opt,name=min,proto3" json:"min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Salary) Reset() {
	*x = Salary{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Salary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salary) ProtoMessage() {}

func (x *Salary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salary.ProtoReflect.Descriptor instead.
func (*Salary) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{12}
}

func (x *Salary) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Salary) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Salary) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

type SalaryRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Period        string                 `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"` // hourly, monthly, yearly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalaryRange) Reset() {
	*x = SalaryRange{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalaryRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaryRange) ProtoMessage() {}

func (x *SalaryRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaryRange.ProtoReflect.Descriptor instead.
func (*SalaryRange) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{13}
}

func (x *SalaryRange) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SalaryRange) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *SalaryRange) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SalaryRange) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type JobPosting struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Company         string                 `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Location        string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Remote          bool                   `protobuf:"varint,5,opt,name=remote,proto3" json:"remote,omitempty"`
	Salary          *SalaryRange           `protobuf:"bytes,6,opt,name=salary,proto3" json:"salary,omitempty"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Requirements    []string               `protobuf:"bytes,8,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Skills          []string               `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	Benefits        []string               `protobuf:"bytes,10,rep,name=benefits,proto3" json:"benefits,omitempty"`
	ExperienceLevel string                 `protobuf:"bytes,11,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	JobType         string                 `protobuf:"bytes,12,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	PostedDate      string                 `protobuf:"bytes,13,opt,name=posted_date,json=postedDate,proto3" json:"posted_date,omitempty"` // ISO timestamp string
	ApplicationUrl  string                 `protobuf:"bytes,14,opt,name=application_url,json=applicationUrl,proto3" json:"application_url,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ProcessedAt     string                 `protobuf:"bytes,16,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"` // ISO timestamp string
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobPosting) Reset() {
	*x = JobPosting{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPosting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPosting) ProtoMessage() {}

func (x *JobPosting) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobPosting.ProtoReflect.Descriptor instead.
func (*JobPosting) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{14}
}

func (x *JobPosting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobPosting) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobPosting) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *JobPosting) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobPosting) GetRemote() bool {
	if x != nil {
		return x.Remote
	}
	return false
}

func (x *JobPosting) GetSalary() *SalaryRange {
	if x != nil {
		return x.Salary
	}
	return nil
}

func (x *JobPosting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobPosting) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *JobPosting) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *JobPosting) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

func (x *JobPosting) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *JobPosting) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *JobPosting) GetPostedDate() string {
	if x != nil {
		return x.PostedDate
	}
	return ""
}

func (x *JobPosting) GetApplicationUrl() string {
	if x != nil {
		return x.ApplicationUrl
	}
	return ""
}

func (x *JobPosting) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *JobPosting) GetProcessedAt() string {
	if x != nil {
		return x.ProcessedAt
	}
	return ""
}

type ScrapeOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Engine         string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"` // "headed", "raw", "auto"
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	LlmProvider    string                 `protobuf:"bytes,3,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"` // "openai", "claude", "local"
	UserAgent      string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Proxy          string                 `protobuf:"bytes,5,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScrapeOptions) Reset() {
	*x = ScrapeOptions{}
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeOptions) ProtoMessage() {}

func (x *ScrapeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeOptions.ProtoReflect.Descriptor instead.
func (*ScrapeOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP(), []int{15}
}

func (x *ScrapeOptions) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *ScrapeOptions) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ScrapeOptions) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *ScrapeOptions) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ScrapeOptions) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

var File_api_proto_letraz_v1_letraz_utils_proto protoreflect.FileDescriptor

const file_api_proto_letraz_v1_letraz_utils_proto_rawDesc = "" +
	"\n" +
	"&api/proto/letraz/v1/letraz-utils.proto\x12\tletraz.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x9c\x01\n" +
	"\x10ScrapeJobRequest\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x122\n" +
	"\aoptions\x18\x03 \x01(\v2\x18.letraz.v1.ScrapeOptionsR\aoptionsB\x06\n" +
	"\x04_urlB\x0e\n" +
	"\f_description\"\x97\x01\n" +
	"\x11ScrapeJobResponse\x12\x1c\n" +
	"\tprocessId\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x8b\x01\n" +
	"\n" +
	"BaseResume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04base\x18\x02 \x01(\bR\x04base\x12#\n" +
	"\x04user\x18\x03 \x01(\v2\x0f.letraz.v1.UserR\x04user\x124\n" +
	"\bsections\x18\x04 \x03(\v2\x18.letraz.v1.ResumeSectionR\bsections\"\xa3\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x10\n" +
	"\x03dob\x18\a \x01(\tR\x03dob\x12 \n" +
	"\vnationality\x18\b \x01(\tR\vnationality\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\tR\x04city\x12\x16\n" +
	"\x06postal\x18\v \x01(\tR\x06postal\x12\x18\n" +
	"\acountry\x18\f \x01(\tR\acountry\x12\x18\n" +
	"\awebsite\x18\r \x01(\tR\awebsite\x12!\n" +
	"\fprofile_text\x18\x0e \x01(\tR\vprofileText\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\"\x8e\x01\n" +
	"\rResumeSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06resume\x18\x02 \x01(\tR\x06resume\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12+\n" +
	"\x04data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04data\"\x8c\x01\n" +
	"\x13TailorResumeRequest\x126\n" +
	"\vbase_resume\x18\x01 \x01(\v2\x15.letraz.v1.BaseResumeR\n" +
	"baseResume\x12 \n" +
	"\x03job\x18\x02 \x01(\v2\x0e.letraz.v1.JobR\x03job\x12\x1b\n" +
	"\tresume_id\x18\x03 \x01(\tR\bresumeId\"\x9a\x01\n" +
	"\x14TailorResumeResponse\x12\x1c\n" +
	"\tprocessId\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"6\n" +
	"\x17ResumeScreenshotRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\tR\bresumeId\"\xc6\x01\n" +
	"\x18ResumeScreenshotResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"process_id\x18\x04 \x01(\tR\tprocessId\x12%\n" +
	"\x0escreenshot_url\x18\x05 \x01(\tR\rscreenshotUrl\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"\x8b\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12B\n" +
	"\x06checks\x18\x05 \x03(\v2*.letraz.v1.HealthCheckResponse.ChecksEntryR\x06checks\x1a9\n" +
	"\vChecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\ajob_url\x18\x03 \x01(\tR\x06jobUrl\x12!\n" +
	"\fcompany_name\x18\x04 \x01(\tR\vcompanyName\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12)\n" +
	"\x06salary\x18\x06 \x01(\v2\x11.letraz.v1.SalaryR\x06salary\x12\"\n" +
	"\frequirements\x18\a \x03(\tR\frequirements\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12*\n" +
	"\x10responsibilities\x18\t \x03(\tR\x10responsibilities\x12\x1a\n" +
	"\bbenefits\x18\n" +
	" \x03(\tR\bbenefits\"H\n" +
	"\x06Salary\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x05R\x03min\"e\n" +
	"\vSalaryRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06period\x18\x04 \x01(\tR\x06period\"\xdb\x04\n" +
	"\n" +
	"JobPosting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x16\n" +
	"\x06remote\x18\x05 \x01(\bR\x06remote\x12.\n" +
	"\x06salary\x18\x06 \x01(\v2\x16.letraz.v1.SalaryRangeR\x06salary\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\b \x03(\tR\frequirements\x12\x16\n" +
	"\x06skills\x18\t \x03(\tR\x06skills\x12\x1a\n" +
	"\bbenefits\x18\n" +
	" \x03(\tR\bbenefits\x12)\n" +
	"\x10experience_level\x18\v \x01(\tR\x0fexperienceLevel\x12\x19\n" +
	"\bjob_type\x18\f \x01(\tR\ajobType\x12\x1f\n" +
	"\vposted_date\x18\r \x01(\tR\n" +
	"postedDate\x12'\n" +
	"\x0fapplication_url\x18\x0e \x01(\tR\x0eapplicationUrl\x12?\n" +
	"\bmetadata\x18\x0f \x03(\v2#.letraz.v1.JobPosting.MetadataEntryR\bmetadata\x12!\n" +
	"\fprocessed_at\x18\x10 \x01(\tR\vprocessedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\rScrapeOptions\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12!\n" +
	"\fllm_provider\x18\x03 \x01(\tR\vllmProvider\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x14\n" +
	"\x05proxy\x18\x05 \x01(\tR\x05proxy2X\n" +
	"\x0eScraperService\x12F\n" +
	"\tScrapeJob\x12\x1b.letraz.v1.ScrapeJobRequest\x1a\x1c.letraz.v1.ScrapeJobResponse2\xbf\x01\n" +
	"\rResumeService\x12O\n" +
	"\fTailorResume\x12\x1e.letraz.v1.TailorResumeRequest\x1a\x1f.letraz.v1.TailorResumeResponse\x12]\n" +
	"\x12GenerateScreenshot\x12\".letraz.v1.ResumeScreenshotRequest\x1a#.letraz.v1.ResumeScreenshotResponse2]\n" +
	"\rHealthService\x12L\n" +
	"\vHealthCheck\x12\x1d.letraz.v1.HealthCheckRequest\x1a\x1e.letraz.v1.HealthCheckResponseB+Z)letraz-utils/api/proto/letraz/v1;letrazv1b\x06proto3"

var (
	file_api_proto_letraz_v1_letraz_utils_proto_rawDescOnce sync.Once
	file_api_proto_letraz_v1_letraz_utils_proto_rawDescData []byte
)

func file_api_proto_letraz_v1_letraz_utils_proto_rawDescGZIP() []byte {
	file_api_proto_letraz_v1_letraz_utils_proto_rawDescOnce.Do(func() {
		file_api_proto_letraz_v1_letraz_utils_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_letraz_v1_letraz_utils_proto_rawDesc), len(file_api_proto_letraz_v1_letraz_utils_proto_rawDesc)))
	})
	return file_api_proto_letraz_v1_letraz_utils_proto_rawDescData
}

var file_api_proto_letraz_v1_letraz_utils_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_letraz_v1_letraz_utils_proto_goTypes = []any{
	(*ScrapeJobRequest)(nil),         // 0: letraz.v1.ScrapeJobRequest
	(*ScrapeJobResponse)(nil),        // 1: letraz.v1.ScrapeJobResponse
	(*BaseResume)(nil),               // 2: letraz.v1.BaseResume
	(*User)(nil),                     // 3: letraz.v1.User
	(*ResumeSection)(nil),            // 4: letraz.v1.ResumeSection
	(*TailorResumeRequest)(nil),      // 5: letraz.v1.TailorResumeRequest
	(*TailorResumeResponse)(nil),     // 6: letraz.v1.TailorResumeResponse
	(*ResumeScreenshotRequest)(nil),  // 7: letraz.v1.ResumeScreenshotRequest
	(*ResumeScreenshotResponse)(nil), // 8: letraz.v1.ResumeScreenshotResponse
	(*HealthCheckRequest)(nil),       // 9: letraz.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 10: letraz.v1.HealthCheckResponse
	(*Job)(nil),                      // 11: letraz.v1.Job
	(*Salary)(nil),                   // 12: letraz.v1.Salary
	(*SalaryRange)(nil),              // 13: letraz.v1.SalaryRange
	(*JobPosting)(nil),               // 14: letraz.v1.JobPosting
	(*ScrapeOptions)(nil),            // 15: letraz.v1.ScrapeOptions
	nil,                              // 16: letraz.v1.HealthCheckResponse.ChecksEntry
	nil,                              // 17: letraz.v1.JobPosting.MetadataEntry
	(*structpb.Struct)(nil),          // 18: google.protobuf.Struct
}
var file_api_proto_letraz_v1_letraz_utils_proto_depIdxs = []int32{
	15, // 0: letraz.v1.ScrapeJobRequest.options:type_name -> letraz.v1.ScrapeOptions
	3,  // 1: letraz.v1.BaseResume.user:type_name -> letraz.v1.User
	4,  // 2: letraz.v1.BaseResume.sections:type_name -> letraz.v1.ResumeSection
	18, // 3: letraz.v1.ResumeSection.data:type_name -> google.protobuf.Struct
	2,  // 4: letraz.v1.TailorResumeRequest.base_resume:type_name -> letraz.v1.BaseResume
	11, // 5: letraz.v1.TailorResumeRequest.job:type_name -> letraz.v1.Job
	16, // 6: letraz.v1.HealthCheckResponse.checks:type_name -> letraz.v1.HealthCheckResponse.ChecksEntry
	12, // 7: letraz.v1.Job.salary:type_name -> letraz.v1.Salary
	13, // 8: letraz.v1.JobPosting.salary:type_name -> letraz.v1.SalaryRange
	17, // 9: letraz.v1.JobPosting.metadata:type_name -> letraz.v1.JobPosting.MetadataEntry
	0,  // 10: letraz.v1.ScraperService.ScrapeJob:input_type -> letraz.v1.ScrapeJobRequest
	5,  // 11: letraz.v1.ResumeService.TailorResume:input_type -> letraz.v1.TailorResumeRequest
	7,  // 12: letraz.v1.ResumeService.GenerateScreenshot:input_type -> letraz.v1.ResumeScreenshotRequest
	9,  // 13: letraz.v1.HealthService.HealthCheck:input_type -> letraz.v1.HealthCheckRequest
	1,  // 14: letraz.v1.ScraperService.ScrapeJob:output_type -> letraz.v1.ScrapeJobResponse
	6,  // 15: letraz.v1.ResumeService.TailorResume:output_type -> letraz.v1.TailorResumeResponse
	8,  // 16: letraz.v1.ResumeService.GenerateScreenshot:output_type -> letraz.v1.ResumeScreenshotResponse
	10, // 17: letraz.v1.HealthService.HealthCheck:output_type -> letraz.v1.HealthCheckResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_letraz_v1_letraz_utils_proto_init() }
func file_api_proto_letraz_v1_letraz_utils_proto_init() {
	if File_api_proto_letraz_v1_letraz_utils_proto != nil {
		return
	}
	file_api_proto_letraz_v1_letraz_utils_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_letraz_v1_letraz_utils_proto_rawDesc), len(file_api_proto_letraz_v1_letraz_utils_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_proto_letraz_v1_letraz_utils_proto_goTypes,
		DependencyIndexes: file_api_proto_letraz_v1_letraz_utils_proto_depIdxs,
		MessageInfos:      file_api_proto_letraz_v1_letraz_utils_proto_msgTypes,
	}.Build()
	File_api_proto_letraz_v1_letraz_utils_proto = out.File
	file_api_proto_letraz_v1_letraz_utils_proto_goTypes = nil
	file_api_proto_letraz_v1_letraz_utils_proto_depIdxs = nil
}
