// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: api/proto/letraz/v1/resume_callback.proto

package letrazv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TailoredResume *TailoredResumeRequest `protobuf:"bytes,1,opt,name=tailored_resume,json=tailoredResume,proto3" json:"tailored_resume,omitempty"`
	Suggestions    []*SuggestionRequest   `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	ThreadId       string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetTailoredResume() *TailoredResumeRequest {
	if x != nil {
		return x.TailoredResume
	}
	return nil
}

func (x *DataRequest) GetSuggestions() []*SuggestionRequest {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *DataRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type GenerateScreenshotCallBackRequest struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	ProcessId      string                     `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	Status         string                     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Data           *ScreenshotDataRequest     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp      string                     `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Operation      string                     `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	ProcessingTime string                     `protobuf:"bytes,6,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	Metadata       *ScreenshotMetadataRequest `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateScreenshotCallBackRequest) Reset() {
	*x = GenerateScreenshotCallBackRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScreenshotCallBackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScreenshotCallBackRequest) ProtoMessage() {}

func (x *GenerateScreenshotCallBackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScreenshotCallBackRequest.ProtoReflect.Descriptor instead.
func (*GenerateScreenshotCallBackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateScreenshotCallBackRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *GenerateScreenshotCallBackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateScreenshotCallBackRequest) GetData() *ScreenshotDataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GenerateScreenshotCallBackRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GenerateScreenshotCallBackRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *GenerateScreenshotCallBackRequest) GetProcessingTime() string {
	if x != nil {
		return x.ProcessingTime
	}
	return ""
}

func (x *GenerateScreenshotCallBackRequest) GetMetadata() *ScreenshotMetadataRequest {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GenerateScreenshotCallBackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           *string                `protobuf:"bytes,1,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateScreenshotCallBackResponse) Reset() {
	*x = GenerateScreenshotCallBackResponse{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScreenshotCallBackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScreenshotCallBackResponse) ProtoMessage() {}

func (x *GenerateScreenshotCallBackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScreenshotCallBackResponse.ProtoReflect.Descriptor instead.
func (*GenerateScreenshotCallBackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateScreenshotCallBackResponse) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	JobTitle      string                 `protobuf:"bytes,2,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	ResumeId      string                 `protobuf:"bytes,3,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *MetadataRequest) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *MetadataRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

type ScreenshotDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenshotUrl string                 `protobuf:"bytes,1,opt,name=screenshot_url,json=screenshotUrl,proto3" json:"screenshot_url,omitempty"`
	ResumeId      string                 `protobuf:"bytes,2,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	FileSizeBytes int32                  `protobuf:"varint,3,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotDataRequest) Reset() {
	*x = ScreenshotDataRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotDataRequest) ProtoMessage() {}

func (x *ScreenshotDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotDataRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{4}
}

func (x *ScreenshotDataRequest) GetScreenshotUrl() string {
	if x != nil {
		return x.ScreenshotUrl
	}
	return ""
}

func (x *ScreenshotDataRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *ScreenshotDataRequest) GetFileSizeBytes() int32 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

type ScreenshotMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileSize      int32                  `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ResumeId      string                 `protobuf:"bytes,2,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	ScreenshotUrl string                 `protobuf:"bytes,3,opt,name=screenshot_url,json=screenshotUrl,proto3" json:"screenshot_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotMetadataRequest) Reset() {
	*x = ScreenshotMetadataRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotMetadataRequest) ProtoMessage() {}

func (x *ScreenshotMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotMetadataRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{5}
}

func (x *ScreenshotMetadataRequest) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ScreenshotMetadataRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *ScreenshotMetadataRequest) GetScreenshotUrl() string {
	if x != nil {
		return x.ScreenshotUrl
	}
	return ""
}

type SectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionRequest) Reset() {
	*x = SectionRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionRequest) ProtoMessage() {}

func (x *SectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionRequest.ProtoReflect.Descriptor instead.
func (*SectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{6}
}

func (x *SectionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SectionRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type SuggestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Impact        string                 `protobuf:"bytes,4,opt,name=impact,proto3" json:"impact,omitempty"`
	Section       string                 `protobuf:"bytes,5,opt,name=section,proto3" json:"section,omitempty"`
	Current       string                 `protobuf:"bytes,6,opt,name=current,proto3" json:"current,omitempty"`
	Suggested     string                 `protobuf:"bytes,7,opt,name=suggested,proto3" json:"suggested,omitempty"`
	Reasoning     string                 `protobuf:"bytes,8,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionRequest) Reset() {
	*x = SuggestionRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionRequest) ProtoMessage() {}

func (x *SuggestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionRequest.ProtoReflect.Descriptor instead.
func (*SuggestionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{7}
}

func (x *SuggestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SuggestionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SuggestionRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *SuggestionRequest) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *SuggestionRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *SuggestionRequest) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *SuggestionRequest) GetSuggested() string {
	if x != nil {
		return x.Suggested
	}
	return ""
}

func (x *SuggestionRequest) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

type TailorResumeCallBackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessId      string                 `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Data           *DataRequest           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp      string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Operation      string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	ProcessingTime string                 `protobuf:"bytes,6,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	Metadata       *MetadataRequest       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TailorResumeCallBackRequest) Reset() {
	*x = TailorResumeCallBackRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResumeCallBackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResumeCallBackRequest) ProtoMessage() {}

func (x *TailorResumeCallBackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResumeCallBackRequest.ProtoReflect.Descriptor instead.
func (*TailorResumeCallBackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{8}
}

func (x *TailorResumeCallBackRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *TailorResumeCallBackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TailorResumeCallBackRequest) GetData() *DataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TailorResumeCallBackRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TailorResumeCallBackRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TailorResumeCallBackRequest) GetProcessingTime() string {
	if x != nil {
		return x.ProcessingTime
	}
	return ""
}

func (x *TailorResumeCallBackRequest) GetMetadata() *MetadataRequest {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TailorResumeCallBackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           *string                `protobuf:"bytes,1,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailorResumeCallBackResponse) Reset() {
	*x = TailorResumeCallBackResponse{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResumeCallBackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResumeCallBackResponse) ProtoMessage() {}

func (x *TailorResumeCallBackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResumeCallBackResponse.ProtoReflect.Descriptor instead.
func (*TailorResumeCallBackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{9}
}

func (x *TailorResumeCallBackResponse) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type TailoredResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sections      []*SectionRequest      `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailoredResumeRequest) Reset() {
	*x = TailoredResumeRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailoredResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailoredResumeRequest) ProtoMessage() {}

func (x *TailoredResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailoredResumeRequest.ProtoReflect.Descriptor instead.
func (*TailoredResumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{10}
}

func (x *TailoredResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TailoredResumeRequest) GetSections() []*SectionRequest {
	if x != nil {
		return x.Sections
	}
	return nil
}

var File_api_proto_letraz_v1_resume_callback_proto protoreflect.FileDescriptor

const file_api_proto_letraz_v1_resume_callback_proto_rawDesc = "" +
	"\n" +
	")api/proto/letraz/v1/resume_callback.proto\x12\x14letraz_server.RESUME\x1a\x1cgoogle/protobuf/struct.proto\"\xcb\x01\n" +
	"\vDataRequest\x12T\n" +
	"\x0ftailored_resume\x18\x01 \x01(\v2+.letraz_server.RESUME.TailoredResumeRequestR\x0etailoredResume\x12I\n" +
	"\vsuggestions\x18\x02 \x03(\v2'.letraz_server.RESUME.SuggestionRequestR\vsuggestions\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadId\"\xcc\x02\n" +
	"!GenerateScreenshotCallBackRequest\x12\x1c\n" +
	"\tprocessId\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12?\n" +
	"\x04data\x18\x03 \x01(\v2+.letraz_server.RESUME.ScreenshotDataRequestR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12'\n" +
	"\x0fprocessing_time\x18\x06 \x01(\tR\x0eprocessingTime\x12K\n" +
	"\bmetadata\x18\a \x01(\v2/.letraz_server.RESUME.ScreenshotMetadataRequestR\bmetadata\"C\n" +
	"\"GenerateScreenshotCallBackResponse\x12\x15\n" +
	"\x03msg\x18\x01 \x01(\tH\x00R\x03msg\x88\x01\x01B\x06\n" +
	"\x04_msg\"e\n" +
	"\x0fMetadataRequest\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x1b\n" +
	"\tjob_title\x18\x02 \x01(\tR\bjobTitle\x12\x1b\n" +
	"\tresume_id\x18\x03 \x01(\tR\bresumeId\"\x83\x01\n" +
	"\x15ScreenshotDataRequest\x12%\n" +
	"\x0escreenshot_url\x18\x01 \x01(\tR\rscreenshotUrl\x12\x1b\n" +
	"\tresume_id\x18\x02 \x01(\tR\bresumeId\x12&\n" +
	"\x0ffile_size_bytes\x18\x03 \x01(\x05R\rfileSizeBytes\"|\n" +
	"\x19ScreenshotMetadataRequest\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\x05R\bfileSize\x12\x1b\n" +
	"\tresume_id\x18\x02 \x01(\tR\bresumeId\x12%\n" +
	"\x0escreenshot_url\x18\x03 \x01(\tR\rscreenshotUrl\"Q\n" +
	"\x0eSectionRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"\xdb\x01\n" +
	"\x11SuggestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x16\n" +
	"\x06impact\x18\x04 \x01(\tR\x06impact\x12\x18\n" +
	"\asection\x18\x05 \x01(\tR\asection\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\tR\acurrent\x12\x1c\n" +
	"\tsuggested\x18\a \x01(\tR\tsuggested\x12\x1c\n" +
	"\treasoning\x18\b \x01(\tR\treasoning\"\xb2\x02\n" +
	"\x1bTailorResumeCallBackRequest\x12\x1c\n" +
	"\tprocessId\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x125\n" +
	"\x04data\x18\x03 \x01(\v2!.letraz_server.RESUME.DataRequestR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12'\n" +
	"\x0fprocessing_time\x18\x06 \x01(\tR\x0eprocessingTime\x12A\n" +
	"\bmetadata\x18\a \x01(\v2%.letraz_server.RESUME.MetadataRequestR\bmetadata\"=\n" +
	"\x1cTailorResumeCallBackResponse\x12\x15\n" +
	"\x03msg\x18\x01 \x01(\tH\x00R\x03msg\x88\x01\x01B\x06\n" +
	"\x04_msg\"i\n" +
	"\x15TailoredResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\bsections\x18\x02 \x03(\v2$.letraz_server.RESUME.SectionRequestR\bsections2\xba\x01\n" +
	"$GenerateScreenshotCallBackController\x12\x91\x01\n" +
	"\x1aGenerateScreenshotCallBack\x127.letraz_server.RESUME.GenerateScreenshotCallBackRequest\x1a8.letraz_server.RESUME.GenerateScreenshotCallBackResponse\"\x002\xa1\x01\n" +
	"\x1eTailorResumeCallBackController\x12\x7f\n" +
	"\x14TailorResumeCallBack\x121.letraz_server.RESUME.TailorResumeCallBackRequest\x1a2.letraz_server.RESUME.TailorResumeCallBackResponse\"\x00B+Z)letraz-utils/api/proto/letraz/v1;letrazv1b\x06proto3"

var (
	file_api_proto_letraz_v1_resume_callback_proto_rawDescOnce sync.Once
	file_api_proto_letraz_v1_resume_callback_proto_rawDescData []byte
)

func file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP() []byte {
	file_api_proto_letraz_v1_resume_callback_proto_rawDescOnce.Do(func() {
		file_api_proto_letraz_v1_resume_callback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_letraz_v1_resume_callback_proto_rawDesc), len(file_api_proto_letraz_v1_resume_callback_proto_rawDesc)))
	})
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescData
}

var file_api_proto_letraz_v1_resume_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_letraz_v1_resume_callback_proto_goTypes = []any{
	(*DataRequest)(nil),                        // 0: letraz_server.RESUME.DataRequest
	(*GenerateScreenshotCallBackRequest)(nil),  // 1: letraz_server.RESUME.GenerateScreenshotCallBackRequest
	(*GenerateScreenshotCallBackResponse)(nil), // 2: letraz_server.RESUME.GenerateScreenshotCallBackResponse
	(*MetadataRequest)(nil),                    // 3: letraz_server.RESUME.MetadataRequest
	(*ScreenshotDataRequest)(nil),              // 4: letraz_server.RESUME.ScreenshotDataRequest
	(*ScreenshotMetadataRequest)(nil),          // 5: letraz_server.RESUME.ScreenshotMetadataRequest
	(*SectionRequest)(nil),                     // 6: letraz_server.RESUME.SectionRequest
	(*SuggestionRequest)(nil),                  // 7: letraz_server.RESUME.SuggestionRequest
	(*TailorResumeCallBackRequest)(nil),        // 8: letraz_server.RESUME.TailorResumeCallBackRequest
	(*TailorResumeCallBackResponse)(nil),       // 9: letraz_server.RESUME.TailorResumeCallBackResponse
	(*TailoredResumeRequest)(nil),              // 10: letraz_server.RESUME.TailoredResumeRequest
	(*structpb.Struct)(nil),                    // 11: google.protobuf.Struct
}
var file_api_proto_letraz_v1_resume_callback_proto_depIdxs = []int32{
	10, // 0: letraz_server.RESUME.DataRequest.tailored_resume:type_name -> letraz_server.RESUME.TailoredResumeRequest
	7,  // 1: letraz_server.RESUME.DataRequest.suggestions:type_name -> letraz_server.RESUME.SuggestionRequest
	4,  // 2: letraz_server.RESUME.GenerateScreenshotCallBackRequest.data:type_name -> letraz_server.RESUME.ScreenshotDataRequest
	5,  // 3: letraz_server.RESUME.GenerateScreenshotCallBackRequest.metadata:type_name -> letraz_server.RESUME.ScreenshotMetadataRequest
	11, // 4: letraz_server.RESUME.SectionRequest.data:type_name -> google.protobuf.Struct
	0,  // 5: letraz_server.RESUME.TailorResumeCallBackRequest.data:type_name -> letraz_server.RESUME.DataRequest
	3,  // 6: letraz_server.RESUME.TailorResumeCallBackRequest.metadata:type_name -> letraz_server.RESUME.MetadataRequest
	6,  // 7: letraz_server.RESUME.TailoredResumeRequest.sections:type_name -> letraz_server.RESUME.SectionRequest
	1,  // 8: letraz_server.RESUME.GenerateScreenshotCallBackController.GenerateScreenshotCallBack:input_type -> letraz_server.RESUME.GenerateScreenshotCallBackRequest
	8,  // 9: letraz_server.RESUME.TailorResumeCallBackController.TailorResumeCallBack:input_type -> letraz_server.RESUME.TailorResumeCallBackRequest
	2,  // 10: letraz_server.RESUME.GenerateScreenshotCallBackController.GenerateScreenshotCallBack:output_type -> letraz_server.RESUME.GenerateScreenshotCallBackResponse
	9,  // 11: letraz_server.RESUME.TailorResumeCallBackController.TailorResumeCallBack:output_type -> letraz_server.RESUME.TailorResumeCallBackResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_letraz_v1_resume_callback_proto_init() }
func file_api_proto_letraz_v1_resume_callback_proto_init() {
	if File_api_proto_letraz_v1_resume_callback_proto != nil {
		return
	}
	file_api_proto_letraz_v1_resume_callback_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_letraz_v1_resume_callback_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_letraz_v1_resume_callback_proto_rawDesc), len(file_api_proto_letraz_v1_resume_callback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_letraz_v1_resume_callback_proto_goTypes,
		DependencyIndexes: file_api_proto_letraz_v1_resume_callback_proto_depIdxs,
		MessageInfos:      file_api_proto_letraz_v1_resume_callback_proto_msgTypes,
	}.Build()
	File_api_proto_letraz_v1_resume_callback_proto = out.File
	file_api_proto_letraz_v1_resume_callback_proto_goTypes = nil
	file_api_proto_letraz_v1_resume_callback_proto_depIdxs = nil
}
