// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/letraz/v1/resume_callback.proto

package letrazv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TailorResume Callback Messages
type TailorResumeCallbackRequest struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	ProcessId      string                       `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	Status         string                       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Data           *TailorResumeDataRequest     `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Timestamp      string                       `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Operation      string                       `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	ProcessingTime string                       `protobuf:"bytes,6,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	Metadata       *TailorResumeMetadataRequest `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TailorResumeCallbackRequest) Reset() {
	*x = TailorResumeCallbackRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResumeCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResumeCallbackRequest) ProtoMessage() {}

func (x *TailorResumeCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResumeCallbackRequest.ProtoReflect.Descriptor instead.
func (*TailorResumeCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{0}
}

func (x *TailorResumeCallbackRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *TailorResumeCallbackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TailorResumeCallbackRequest) GetData() *TailorResumeDataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TailorResumeCallbackRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TailorResumeCallbackRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TailorResumeCallbackRequest) GetProcessingTime() string {
	if x != nil {
		return x.ProcessingTime
	}
	return ""
}

func (x *TailorResumeCallbackRequest) GetMetadata() *TailorResumeMetadataRequest {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TailorResumeCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           *string                `protobuf:"bytes,1,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailorResumeCallbackResponse) Reset() {
	*x = TailorResumeCallbackResponse{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResumeCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResumeCallbackResponse) ProtoMessage() {}

func (x *TailorResumeCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResumeCallbackResponse.ProtoReflect.Descriptor instead.
func (*TailorResumeCallbackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{1}
}

func (x *TailorResumeCallbackResponse) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type TailorResumeDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TailoredResume *TailoredResumeRequest `protobuf:"bytes,1,opt,name=tailored_resume,json=tailoredResume,proto3" json:"tailored_resume,omitempty"`
	Suggestions    []*SuggestionRequest   `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	ThreadId       string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TailorResumeDataRequest) Reset() {
	*x = TailorResumeDataRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResumeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResumeDataRequest) ProtoMessage() {}

func (x *TailorResumeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResumeDataRequest.ProtoReflect.Descriptor instead.
func (*TailorResumeDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{2}
}

func (x *TailorResumeDataRequest) GetTailoredResume() *TailoredResumeRequest {
	if x != nil {
		return x.TailoredResume
	}
	return nil
}

func (x *TailorResumeDataRequest) GetSuggestions() []*SuggestionRequest {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *TailorResumeDataRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type TailorResumeMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	JobTitle      string                 `protobuf:"bytes,2,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	ResumeId      string                 `protobuf:"bytes,3,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailorResumeMetadataRequest) Reset() {
	*x = TailorResumeMetadataRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResumeMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResumeMetadataRequest) ProtoMessage() {}

func (x *TailorResumeMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResumeMetadataRequest.ProtoReflect.Descriptor instead.
func (*TailorResumeMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{3}
}

func (x *TailorResumeMetadataRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *TailorResumeMetadataRequest) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *TailorResumeMetadataRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

type TailoredResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sections      []*SectionRequest      `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailoredResumeRequest) Reset() {
	*x = TailoredResumeRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailoredResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailoredResumeRequest) ProtoMessage() {}

func (x *TailoredResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailoredResumeRequest.ProtoReflect.Descriptor instead.
func (*TailoredResumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{4}
}

func (x *TailoredResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TailoredResumeRequest) GetSections() []*SectionRequest {
	if x != nil {
		return x.Sections
	}
	return nil
}

type SectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionRequest) Reset() {
	*x = SectionRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionRequest) ProtoMessage() {}

func (x *SectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionRequest.ProtoReflect.Descriptor instead.
func (*SectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{5}
}

func (x *SectionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SectionRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type SuggestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Impact        string                 `protobuf:"bytes,4,opt,name=impact,proto3" json:"impact,omitempty"`
	Section       string                 `protobuf:"bytes,5,opt,name=section,proto3" json:"section,omitempty"`
	Current       string                 `protobuf:"bytes,6,opt,name=current,proto3" json:"current,omitempty"`
	Suggested     string                 `protobuf:"bytes,7,opt,name=suggested,proto3" json:"suggested,omitempty"`
	Reasoning     string                 `protobuf:"bytes,8,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionRequest) Reset() {
	*x = SuggestionRequest{}
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionRequest) ProtoMessage() {}

func (x *SuggestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_letraz_v1_resume_callback_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionRequest.ProtoReflect.Descriptor instead.
func (*SuggestionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP(), []int{6}
}

func (x *SuggestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SuggestionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SuggestionRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *SuggestionRequest) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *SuggestionRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *SuggestionRequest) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *SuggestionRequest) GetSuggested() string {
	if x != nil {
		return x.Suggested
	}
	return ""
}

func (x *SuggestionRequest) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

var File_api_proto_letraz_v1_resume_callback_proto protoreflect.FileDescriptor

const file_api_proto_letraz_v1_resume_callback_proto_rawDesc = "" +
	"\n" +
	")api/proto/letraz/v1/resume_callback.proto\x12\x14letraz_server.RESUME\x1a\x1cgoogle/protobuf/struct.proto\"\xea\x02\n" +
	"\x1bTailorResumeCallbackRequest\x12\x1c\n" +
	"\tprocessId\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12F\n" +
	"\x04data\x18\x03 \x01(\v2-.letraz_server.RESUME.TailorResumeDataRequestH\x00R\x04data\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12'\n" +
	"\x0fprocessing_time\x18\x06 \x01(\tR\x0eprocessingTime\x12R\n" +
	"\bmetadata\x18\a \x01(\v21.letraz_server.RESUME.TailorResumeMetadataRequestH\x01R\bmetadata\x88\x01\x01B\a\n" +
	"\x05_dataB\v\n" +
	"\t_metadata\"=\n" +
	"\x1cTailorResumeCallbackResponse\x12\x15\n" +
	"\x03msg\x18\x01 \x01(\tH\x00R\x03msg\x88\x01\x01B\x06\n" +
	"\x04_msg\"\xd7\x01\n" +
	"\x17TailorResumeDataRequest\x12T\n" +
	"\x0ftailored_resume\x18\x01 \x01(\v2+.letraz_server.RESUME.TailoredResumeRequestR\x0etailoredResume\x12I\n" +
	"\vsuggestions\x18\x02 \x03(\v2'.letraz_server.RESUME.SuggestionRequestR\vsuggestions\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadId\"q\n" +
	"\x1bTailorResumeMetadataRequest\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x1b\n" +
	"\tjob_title\x18\x02 \x01(\tR\bjobTitle\x12\x1b\n" +
	"\tresume_id\x18\x03 \x01(\tR\bresumeId\"i\n" +
	"\x15TailoredResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\bsections\x18\x02 \x03(\v2$.letraz_server.RESUME.SectionRequestR\bsections\"Q\n" +
	"\x0eSectionRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"\xdb\x01\n" +
	"\x11SuggestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x16\n" +
	"\x06impact\x18\x04 \x01(\tR\x06impact\x12\x18\n" +
	"\asection\x18\x05 \x01(\tR\asection\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\tR\acurrent\x12\x1c\n" +
	"\tsuggested\x18\a \x01(\tR\tsuggested\x12\x1c\n" +
	"\treasoning\x18\b \x01(\tR\treasoning2\xa1\x01\n" +
	"\x1eTailorResumeCallBackController\x12\x7f\n" +
	"\x14TailorResumeCallBack\x121.letraz_server.RESUME.TailorResumeCallbackRequest\x1a2.letraz_server.RESUME.TailorResumeCallbackResponse\"\x00B+Z)letraz-utils/api/proto/letraz/v1;letrazv1b\x06proto3"

var (
	file_api_proto_letraz_v1_resume_callback_proto_rawDescOnce sync.Once
	file_api_proto_letraz_v1_resume_callback_proto_rawDescData []byte
)

func file_api_proto_letraz_v1_resume_callback_proto_rawDescGZIP() []byte {
	file_api_proto_letraz_v1_resume_callback_proto_rawDescOnce.Do(func() {
		file_api_proto_letraz_v1_resume_callback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_letraz_v1_resume_callback_proto_rawDesc), len(file_api_proto_letraz_v1_resume_callback_proto_rawDesc)))
	})
	return file_api_proto_letraz_v1_resume_callback_proto_rawDescData
}

var file_api_proto_letraz_v1_resume_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_letraz_v1_resume_callback_proto_goTypes = []any{
	(*TailorResumeCallbackRequest)(nil),  // 0: letraz_server.RESUME.TailorResumeCallbackRequest
	(*TailorResumeCallbackResponse)(nil), // 1: letraz_server.RESUME.TailorResumeCallbackResponse
	(*TailorResumeDataRequest)(nil),      // 2: letraz_server.RESUME.TailorResumeDataRequest
	(*TailorResumeMetadataRequest)(nil),  // 3: letraz_server.RESUME.TailorResumeMetadataRequest
	(*TailoredResumeRequest)(nil),        // 4: letraz_server.RESUME.TailoredResumeRequest
	(*SectionRequest)(nil),               // 5: letraz_server.RESUME.SectionRequest
	(*SuggestionRequest)(nil),            // 6: letraz_server.RESUME.SuggestionRequest
	(*structpb.Struct)(nil),              // 7: google.protobuf.Struct
}
var file_api_proto_letraz_v1_resume_callback_proto_depIdxs = []int32{
	2, // 0: letraz_server.RESUME.TailorResumeCallbackRequest.data:type_name -> letraz_server.RESUME.TailorResumeDataRequest
	3, // 1: letraz_server.RESUME.TailorResumeCallbackRequest.metadata:type_name -> letraz_server.RESUME.TailorResumeMetadataRequest
	4, // 2: letraz_server.RESUME.TailorResumeDataRequest.tailored_resume:type_name -> letraz_server.RESUME.TailoredResumeRequest
	6, // 3: letraz_server.RESUME.TailorResumeDataRequest.suggestions:type_name -> letraz_server.RESUME.SuggestionRequest
	5, // 4: letraz_server.RESUME.TailoredResumeRequest.sections:type_name -> letraz_server.RESUME.SectionRequest
	7, // 5: letraz_server.RESUME.SectionRequest.data:type_name -> google.protobuf.Struct
	0, // 6: letraz_server.RESUME.TailorResumeCallBackController.TailorResumeCallBack:input_type -> letraz_server.RESUME.TailorResumeCallbackRequest
	1, // 7: letraz_server.RESUME.TailorResumeCallBackController.TailorResumeCallBack:output_type -> letraz_server.RESUME.TailorResumeCallbackResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_letraz_v1_resume_callback_proto_init() }
func file_api_proto_letraz_v1_resume_callback_proto_init() {
	if File_api_proto_letraz_v1_resume_callback_proto != nil {
		return
	}
	file_api_proto_letraz_v1_resume_callback_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_letraz_v1_resume_callback_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_letraz_v1_resume_callback_proto_rawDesc), len(file_api_proto_letraz_v1_resume_callback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_letraz_v1_resume_callback_proto_goTypes,
		DependencyIndexes: file_api_proto_letraz_v1_resume_callback_proto_depIdxs,
		MessageInfos:      file_api_proto_letraz_v1_resume_callback_proto_msgTypes,
	}.Build()
	File_api_proto_letraz_v1_resume_callback_proto = out.File
	file_api_proto_letraz_v1_resume_callback_proto_goTypes = nil
	file_api_proto_letraz_v1_resume_callback_proto_depIdxs = nil
}
