server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "60s"  # Increased for AI processing responses
  idle_timeout: "60s"

workers:
  pool_size: 10
  queue_size: 100
  rate_limit: 60  # requests per minute
  timeout: "30s"
  max_retries: 3

background_tasks:
  max_concurrent_tasks: 50
  task_timeout: "300s"
  cleanup_interval: "1h"
  max_task_age: "24h"

llm:
  provider: "claude"
  api_key: ""  # Set via environment variable LLM_API_KEY
  max_tokens: 4096
  temperature: 0.1
  timeout: "60s"

scraper:
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  proxies: []
  max_retries: 3
  request_timeout: "30s"
  headless_mode: true
  stealth_mode: true
  captcha:
    provider: "2captcha"
    api_key: ""  # Set via environment variable CAPTCHA_API_KEY
    timeout: "30s"
    enable_auto_solve: true

firecrawl:
  api_key: ""  # Set via environment variable FIRECRAWL_API_KEY
  api_url: "https://api.firecrawl.dev"
  version: "v1"
  timeout: "60s"
  max_retries: 3
  formats: ["markdown"]  # Default formats: markdown, html, rawHtml, links, screenshot

logging:
  level: "debug"  # Changed from "warn" to "debug" for troubleshooting captcha issues
  format: "json"
  output: "stdout" 