# Example configuration for the new logging system
# This file demonstrates how to configure different logging adapters

server:
  port: 8080
  host: "0.0.0.0"
  # ... other server config ...

logging:
  level: "info"
  format: "json"  # Legacy format (for backward compatibility)
  output: "stdout"  # Legacy output (for backward compatibility)
  
  # New adapter-based configuration
  adapters:
    # Standard output adapter
    - name: "console"
      type: "stdout"
      enabled: true
      options:
        format: "json"
        colorized: false
    
    # File adapter with size-based rotation
    - name: "app_log"
      type: "file"
      enabled: true
      options:
        file_path: "./logs/app.log"
        format: "json"
        max_size: 104857600  # 100MB
        max_backups: 5
        compress: true
        create_dirs: true
        sync_on_write: false
        rotation_policy: "size"
    
    # Error log file (errors and fatals only)
    - name: "error_log"
      type: "file"
      enabled: true
      options:
        file_path: "./logs/error.log"
        format: "json"
        max_size: 52428800  # 50MB
        max_backups: 10
        compress: true
        create_dirs: true
        sync_on_write: true
        rotation_policy: "size"
    
    # Debug log file with time-based rotation
    - name: "debug_log"
      type: "file"
      enabled: false  # Enable only during development
      options:
        file_path: "./logs/debug.log"
        format: "text"
        max_age: "24h"
        max_backups: 3
        compress: false
        create_dirs: true
        sync_on_write: false
        rotation_policy: "time"
    
    # Future: Betterstack integration (Phase 2)
    # - name: "betterstack"
    #   type: "betterstack"
    #   enabled: true
    #   options:
    #     source_token: "${BETTERSTACK_SOURCE_TOKEN}"
    #     endpoint: "https://in.logs.betterstack.com"
    #     batch_size: 100
    #     flush_interval: "5s"
    #     max_retries: 3
    #     circuit_breaker:
    #       failure_threshold: 5
    #       reset_timeout: "30s"

# ... other application config ... 